/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class AGREEMENTALREADYCANCELLED {
  'issue'?: AGREEMENTALREADYCANCELLED.IssueEnum;
  'description'?: AGREEMENTALREADYCANCELLED.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'AGREEMENTALREADYCANCELLED.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'AGREEMENTALREADYCANCELLED.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return AGREEMENTALREADYCANCELLED.attributeTypeMap;
  }
}

export namespace AGREEMENTALREADYCANCELLED {
  export enum IssueEnum {
    AgreementAlreadyCancelled = <any>'AGREEMENT_ALREADY_CANCELLED',
  }
  export enum DescriptionEnum {
    TheRequestedAgreementIsAlreadyCanceled = <any>(
      'The requested agreement is already canceled.'
    ),
  }
}
