/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class AMOUNTCHANGENOTALLOWED {
  'issue'?: AMOUNTCHANGENOTALLOWED.IssueEnum;
  'description'?: AMOUNTCHANGENOTALLOWED.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'AMOUNTCHANGENOTALLOWED.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'AMOUNTCHANGENOTALLOWED.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return AMOUNTCHANGENOTALLOWED.attributeTypeMap;
  }
}

export namespace AMOUNTCHANGENOTALLOWED {
  export enum IssueEnum {
    AmountChangeNotAllowed = <any>'AMOUNT_CHANGE_NOT_ALLOWED',
  }
  export enum DescriptionEnum {
    TheAmountSpecifiedIsDifferentFromTheAmountAuthorizedByPayer = <any>(
      'The amount specified is different from the amount authorized by payer.'
    ),
  }
}
