/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Money } from './money';

/**
 * The breakdown of the amount. Breakdown provides details such as total item amount, total tax amount, shipping, handling, insurance, and discounts, if any.
 */
export class AmountBreakdown {
  'itemTotal'?: Money;
  'shipping'?: Money;
  'handling'?: Money;
  'taxTotal'?: Money;
  'insurance'?: Money;
  'shippingDiscount'?: Money;
  'discount'?: Money;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'itemTotal',
      baseName: 'item_total',
      type: 'Money',
    },
    {
      name: 'shipping',
      baseName: 'shipping',
      type: 'Money',
    },
    {
      name: 'handling',
      baseName: 'handling',
      type: 'Money',
    },
    {
      name: 'taxTotal',
      baseName: 'tax_total',
      type: 'Money',
    },
    {
      name: 'insurance',
      baseName: 'insurance',
      type: 'Money',
    },
    {
      name: 'shippingDiscount',
      baseName: 'shipping_discount',
      type: 'Money',
    },
    {
      name: 'discount',
      baseName: 'discount',
      type: 'Money',
    },
  ];

  static getAttributeTypeMap() {
    return AmountBreakdown.attributeTypeMap;
  }
}
