/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Information about the decrypted apple pay payment data for the token like cryptogram, eci indicator.
 */
export class ApplePayPaymentData {
  /**
   * Online payment cryptogram, as defined by 3D Secure. The pattern is defined by an external party and supports Unicode.
   */
  'cryptogram'?: string;
  /**
   * ECI indicator, as defined by 3- Secure. The pattern is defined by an external party and supports Unicode.
   */
  'eciIndicator'?: string;
  /**
   * Encoded Apple Pay EMV Payment Structure used for payments in China. The pattern is defined by an external party and supports Unicode.
   */
  'emvData'?: string;
  /**
   * Bank Key encrypted Apple Pay PIN. The pattern is defined by an external party and supports Unicode.
   */
  'pin'?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'cryptogram',
      baseName: 'cryptogram',
      type: 'string',
    },
    {
      name: 'eciIndicator',
      baseName: 'eci_indicator',
      type: 'string',
    },
    {
      name: 'emvData',
      baseName: 'emv_data',
      type: 'string',
    },
    {
      name: 'pin',
      baseName: 'pin',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return ApplePayPaymentData.attributeTypeMap;
  }
}
