/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Bank Identification Number (BIN) details used to fund a payment.
 */
export class BinDetails {
  /**
   * The Bank Identification Number (BIN) signifies the number that is being used to identify the granular level details (except the PII information) of the card.
   */
  'bin'?: string;
  /**
   * The issuer of the card instrument.
   */
  'issuingBank'?: string;
  /**
   * The [two-character ISO 3166-1 code](/api/rest/reference/country-codes/) that identifies the country or region.<blockquote><strong>Note:</strong> The country code for Great Britain is <code>GB</code> and not <code>UK</code> as used in the top-level domain names for that country. Use the `C2` country code for China worldwide for comparable uncontrolled price (CUP) method, bank card, and cross-border transactions.</blockquote>
   */
  'binCountryCode'?: string;
  /**
   * The type of card product assigned to the BIN by the issuer. These values are defined by the issuer and may change over time. Some examples include: PREPAID_GIFT, CONSUMER, CORPORATE.
   */
  'products'?: Array<string>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'bin',
      baseName: 'bin',
      type: 'string',
    },
    {
      name: 'issuingBank',
      baseName: 'issuing_bank',
      type: 'string',
    },
    {
      name: 'binCountryCode',
      baseName: 'bin_country_code',
      type: 'string',
    },
    {
      name: 'products',
      baseName: 'products',
      type: 'Array<string>',
    },
  ];

  static getAttributeTypeMap() {
    return BinDetails.attributeTypeMap;
  }
}
