/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class CANCELURLREQUIRED {
  'issue'?: CANCELURLREQUIRED.IssueEnum;
  'description'?: CANCELURLREQUIRED.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'CANCELURLREQUIRED.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'CANCELURLREQUIRED.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return CANCELURLREQUIRED.attributeTypeMap;
  }
}

export namespace CANCELURLREQUIRED {
  export enum IssueEnum {
    CancelUrlRequired = <any>'CANCEL_URL_REQUIRED',
  }
  export enum DescriptionEnum {
    TheCancelUrlIsRequiredWhenAttemptingToVaultThisSource = <any>(
      'The cancel url is required when attempting to vault this source.'
    ),
  }
}
