/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class CANNOTBENEGATIVE {
  'issue'?: CANNOTBENEGATIVE.IssueEnum;
  'description'?: CANNOTBENEGATIVE.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'CANNOTBENEGATIVE.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'CANNOTBENEGATIVE.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return CANNOTBENEGATIVE.attributeTypeMap;
  }
}

export namespace CANNOTBENEGATIVE {
  export enum IssueEnum {
    CannotBeNegative = <any>'CANNOT_BE_NEGATIVE',
  }
  export enum DescriptionEnum {
    MustBeGreaterThanOrEqualTo0IfTheCurrencySupportsDecimalsOnlyTwoDecimalPlacePrecisionIsSupported = <
      any
    >'Must be greater than or equal to 0. If the currency supports decimals, only two decimal place precision is supported.',
  }
}
