/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Level2CardProcessingData } from './level2CardProcessingData';
import { Level3CardProcessingData } from './level3CardProcessingData';

/**
 * Merchants and partners can add Level 2 and 3 data to payments to reduce risk and payment processing costs. For more information about processing payments, see <a href=\"https://developer.paypal.com/docs/checkout/advanced/processing/\">checkout</a> or <a href=\"https://developer.paypal.com/docs/multiparty/checkout/advanced/processing/\">multiparty checkout</a>.
 */
export class CardSupplementaryData {
  'level2'?: Level2CardProcessingData;
  'level3'?: Level3CardProcessingData;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'level2',
      baseName: 'level_2',
      type: 'Level2CardProcessingData',
    },
    {
      name: 'level3',
      baseName: 'level_3',
      type: 'Level3CardProcessingData',
    },
  ];

  static getAttributeTypeMap() {
    return CardSupplementaryData.attributeTypeMap;
  }
}
