/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AuthenticationResponse } from './authenticationResponse';
import { BinDetails } from './binDetails';
import { CardAttributesResponse } from './cardAttributesResponse';
import { CardBrand } from './cardBrand';
import { CardFromRequest } from './cardFromRequest';

/**
 * The payment card to use to fund a payment. Card can be a credit or debit card.
 */
export class CardResponse {
  /**
   * The card holder\'s name as it appears on the card.
   */
  'name'?: string;
  /**
   * The last digits of the payment card.
   */
  'lastDigits'?: string;
  'brand'?: CardBrand;
  /**
   * Array of brands or networks associated with the card.
   */
  'availableNetworks'?: Array<CardBrand>;
  /**
   * The payment card type.
   */
  'type'?: CardResponse.TypeEnum;
  'authenticationResult'?: AuthenticationResponse;
  'attributes'?: CardAttributesResponse;
  'fromRequest'?: CardFromRequest;
  /**
   * The year and month, in ISO-8601 `YYYY-MM` date format. See [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6).
   */
  'expiry'?: string;
  'binDetails'?: BinDetails;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'name',
      baseName: 'name',
      type: 'string',
    },
    {
      name: 'lastDigits',
      baseName: 'last_digits',
      type: 'string',
    },
    {
      name: 'brand',
      baseName: 'brand',
      type: 'CardBrand',
    },
    {
      name: 'availableNetworks',
      baseName: 'available_networks',
      type: 'Array<CardBrand>',
    },
    {
      name: 'type',
      baseName: 'type',
      type: 'CardResponse.TypeEnum',
    },
    {
      name: 'authenticationResult',
      baseName: 'authentication_result',
      type: 'AuthenticationResponse',
    },
    {
      name: 'attributes',
      baseName: 'attributes',
      type: 'CardAttributesResponse',
    },
    {
      name: 'fromRequest',
      baseName: 'from_request',
      type: 'CardFromRequest',
    },
    {
      name: 'expiry',
      baseName: 'expiry',
      type: 'string',
    },
    {
      name: 'binDetails',
      baseName: 'bin_details',
      type: 'BinDetails',
    },
  ];

  static getAttributeTypeMap() {
    return CardResponse.attributeTypeMap;
  }
}

export namespace CardResponse {
  export enum TypeEnum {
    Credit = <any>'CREDIT',
    Debit = <any>'DEBIT',
    Prepaid = <any>'PREPAID',
    Unknown = <any>'UNKNOWN',
  }
}
