/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class CARDEXPIRED {
  'issue'?: CARDEXPIRED.IssueEnum;
  'description'?: CARDEXPIRED.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'CARDEXPIRED.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'CARDEXPIRED.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return CARDEXPIRED.attributeTypeMap;
  }
}

export namespace CARDEXPIRED {
  export enum IssueEnum {
    CardExpired = <any>'CARD_EXPIRED',
  }
  export enum DescriptionEnum {
    TheCardIsExpired = <any>'The card is expired',
  }
}
