/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The card network or brand. Applies to credit, debit, gift, and payment cards.
 */
export enum CardBrand {
  Visa = <any>'VISA',
  Mastercard = <any>'MASTERCARD',
  Discover = <any>'DISCOVER',
  Amex = <any>'AMEX',
  Solo = <any>'SOLO',
  Jcb = <any>'JCB',
  Star = <any>'STAR',
  Delta = <any>'DELTA',
  Switch = <any>'SWITCH',
  Maestro = <any>'MAESTRO',
  CbNationale = <any>'CB_NATIONALE',
  Configoga = <any>'CONFIGOGA',
  Confidis = <any>'CONFIDIS',
  Electron = <any>'ELECTRON',
  Cetelem = <any>'CETELEM',
  ChinaUnionPay = <any>'CHINA_UNION_PAY',
}
