/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class CRYPTOGRAMREQUIRED {
  'issue'?: CRYPTOGRAMREQUIRED.IssueEnum;
  'description'?: CRYPTOGRAMREQUIRED.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'CRYPTOGRAMREQUIRED.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'CRYPTOGRAMREQUIRED.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return CRYPTOGRAMREQUIRED.attributeTypeMap;
  }
}

export namespace CRYPTOGRAMREQUIRED {
  export enum IssueEnum {
    CryptogramRequired = <any>'CRYPTOGRAM_REQUIRED',
  }
  export enum DescriptionEnum {
    CryptogramIsRequiredIfAuthenticationMethodIsCryptogram3Ds = <any>(
      'Cryptogram is required if authentication method is CRYPTOGRAM 3DS.'
    ),
  }
}
