/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class DUPLICATEINVOICEID {
  'issue'?: DUPLICATEINVOICEID.IssueEnum;
  'description'?: DUPLICATEINVOICEID.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'DUPLICATEINVOICEID.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'DUPLICATEINVOICEID.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return DUPLICATEINVOICEID.attributeTypeMap;
  }
}

export namespace DUPLICATEINVOICEID {
  export enum IssueEnum {
    DuplicateInvoiceId = <any>'DUPLICATE_INVOICE_ID',
  }
  export enum DescriptionEnum {
    DuplicateInvoiceIdDetectedToAvoidAPotentialDuplicateTransactionYourAccountSettingRequiresThatInvoiceIdBeUniqueForEachTransaction = <
      any
    >'Duplicate Invoice ID detected. To avoid a potential duplicate transaction your account setting requires that Invoice Id be unique for each transaction.',
  }
}
