/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class IBANCOUNTRYNOTSUPPORTED {
  'issue'?: IBANCOUNTRYNOTSUPPORTED.IssueEnum;
  'description'?: IBANCOUNTRYNOTSUPPORTED.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'IBANCOUNTRYNOTSUPPORTED.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'IBANCOUNTRYNOTSUPPORTED.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return IBANCOUNTRYNOTSUPPORTED.attributeTypeMap;
  }
}

export namespace IBANCOUNTRYNOTSUPPORTED {
  export enum IssueEnum {
    IbanCountryNotSupported = <any>'IBAN_COUNTRY_NOT_SUPPORTED',
  }
  export enum DescriptionEnum {
    CountryCodeOfIssuerBankForTheProvidedIbanIsNotSupportedForSepaDebitPayments = <
      any
    >'Country code of issuer bank for the provided IBAN is not supported for SEPA debit payments.',
  }
}
