/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class INCOMPATIBLEPARAMETERVALUE {
  'issue'?: INCOMPATIBLEPARAMETERVALUE.IssueEnum;
  'description'?: INCOMPATIBLEPARAMETERVALUE.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'INCOMPATIBLEPARAMETERVALUE.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'INCOMPATIBLEPARAMETERVALUE.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return INCOMPATIBLEPARAMETERVALUE.attributeTypeMap;
  }
}

export namespace INCOMPATIBLEPARAMETERVALUE {
  export enum IssueEnum {
    IncompatibleParameterValue = <any>'INCOMPATIBLE_PARAMETER_VALUE',
  }
  export enum DescriptionEnum {
    TheValueOfTheFieldIsIncompatibleRedundantWithOtherFieldsInTheOrder = <any>(
      'The value of the field is incompatible/redundant with other fields in the order.'
    ),
  }
}
