/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class INVALIDPARAMETERVALUE1 {
  'issue'?: INVALIDPARAMETERVALUE1.IssueEnum;
  'description'?: INVALIDPARAMETERVALUE1.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'INVALIDPARAMETERVALUE1.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'INVALIDPARAMETERVALUE1.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return INVALIDPARAMETERVALUE1.attributeTypeMap;
  }
}

export namespace INVALIDPARAMETERVALUE1 {
  export enum IssueEnum {
    InvalidParameterValue = <any>'INVALID_PARAMETER_VALUE',
  }
  export enum DescriptionEnum {
    TheValueOfAFieldIsInvalid = <any>'The value of a field is invalid.',
  }
}
