/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class INVALIDEXPIRYDATE {
  'issue'?: INVALIDEXPIRYDATE.IssueEnum;
  'description'?: INVALIDEXPIRYDATE.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'INVALIDEXPIRYDATE.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'INVALIDEXPIRYDATE.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return INVALIDEXPIRYDATE.attributeTypeMap;
  }
}

export namespace INVALIDEXPIRYDATE {
  export enum IssueEnum {
    InvalidExpiryDate = <any>'INVALID_EXPIRY_DATE',
  }
  export enum DescriptionEnum {
    ExpiryDateIsInvalidExpiryDateShouldBeADateInFutureAndWithinTheThresholdForThePaymentSource = <
      any
    >'Expiry date is invalid. Expiry date should be a date in future and within the threshold for the payment source.',
  }
}
