/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class INVALIDPAYERID {
  'issue'?: INVALIDPAYERID.IssueEnum;
  'description'?: INVALIDPAYERID.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'INVALIDPAYERID.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'INVALIDPAYERID.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return INVALIDPAYERID.attributeTypeMap;
  }
}

export namespace INVALIDPAYERID {
  export enum IssueEnum {
    InvalidPayerId = <any>'INVALID_PAYER_ID',
  }
  export enum DescriptionEnum {
    ThePayerIdIsNotValid = <any>'The payer ID is not valid.',
  }
}
