/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class INVALIDPARAMETER {
  'issue'?: INVALIDPARAMETER.IssueEnum;
  'description'?: INVALIDPARAMETER.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'INVALIDPARAMETER.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'INVALIDPARAMETER.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return INVALIDPARAMETER.attributeTypeMap;
  }
}

export namespace INVALIDPARAMETER {
  export enum IssueEnum {
    InvalidParameter = <any>'INVALID_PARAMETER',
  }
  export enum DescriptionEnum {
    CannotBeSpecifiedAsPartOfTheRequest = <any>(
      'Cannot be specified as part of the request.'
    ),
  }
}
