/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class ITEMTOTALMISMATCH {
  'issue'?: ITEMTOTALMISMATCH.IssueEnum;
  'description'?: ITEMTOTALMISMATCH.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'ITEMTOTALMISMATCH.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'ITEMTOTALMISMATCH.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return ITEMTOTALMISMATCH.attributeTypeMap;
  }
}

export namespace ITEMTOTALMISMATCH {
  export enum IssueEnum {
    ItemTotalMismatch = <any>'ITEM_TOTAL_MISMATCH',
  }
  export enum DescriptionEnum {
    ShouldEqualSumOfUnitAmountQuantityAcrossAllItemsForAGivenPurchaseUnit = <
      any
    >'Should equal sum of (unit_amount * quantity) across all items for a given purchase_unit.',
  }
}
