/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AddressPortable } from './addressPortable';
import { LineItem } from './lineItem';
import { Money } from './money';

/**
 * The level 3 card processing data collections, If your merchant account has been configured for Level 3 processing this field will be passed to the processor on your behalf. Please contact your PayPal Technical Account Manager to define level 3 data for your business.
 */
export class Level3CardProcessingData {
  'shippingAmount'?: Money;
  'dutyAmount'?: Money;
  'discountAmount'?: Money;
  'shippingAddress'?: AddressPortable;
  /**
   * Use this field to specify the postal code of the shipping location.
   */
  'shipsFromPostalCode'?: string;
  /**
   * A list of the items that were purchased with this payment. If your merchant account has been configured for Level 3 processing this field will be passed to the processor on your behalf.
   */
  'lineItems'?: Array<LineItem>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'shippingAmount',
      baseName: 'shipping_amount',
      type: 'Money',
    },
    {
      name: 'dutyAmount',
      baseName: 'duty_amount',
      type: 'Money',
    },
    {
      name: 'discountAmount',
      baseName: 'discount_amount',
      type: 'Money',
    },
    {
      name: 'shippingAddress',
      baseName: 'shipping_address',
      type: 'AddressPortable',
    },
    {
      name: 'shipsFromPostalCode',
      baseName: 'ships_from_postal_code',
      type: 'string',
    },
    {
      name: 'lineItems',
      baseName: 'line_items',
      type: 'Array<LineItem>',
    },
  ];

  static getAttributeTypeMap() {
    return Level3CardProcessingData.attributeTypeMap;
  }
}
