/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class MULTIPLESHIPPINGOPTIONSELECTED {
  'issue'?: MULTIPLESHIPPINGOPTIONSELECTED.IssueEnum;
  'description'?: MULTIPLESHIPPINGOPTIONSELECTED.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'MULTIPLESHIPPINGOPTIONSELECTED.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'MULTIPLESHIPPINGOPTIONSELECTED.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return MULTIPLESHIPPINGOPTIONSELECTED.attributeTypeMap;
  }
}

export namespace MULTIPLESHIPPINGOPTIONSELECTED {
  export enum IssueEnum {
    MultipleShippingOptionSelected = <any>'MULTIPLE_SHIPPING_OPTION_SELECTED',
  }
  export enum DescriptionEnum {
    OnlyOneShippingOptionCanBeSetToSelectedTrue = <any>(
      "Only one shipping.option can be set to 'selected = true'."
    ),
  }
}
