/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class MULTIPLEITEMCATEGORIES {
  'issue'?: MULTIPLEITEMCATEGORIES.IssueEnum;
  'description'?: MULTIPLEITEMCATEGORIES.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'MULTIPLEITEMCATEGORIES.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'MULTIPLEITEMCATEGORIES.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return MULTIPLEITEMCATEGORIES.attributeTypeMap;
  }
}

export namespace MULTIPLEITEMCATEGORIES {
  export enum IssueEnum {
    MultipleItemCategories = <any>'MULTIPLE_ITEM_CATEGORIES',
  }
  export enum DescriptionEnum {
    ForAGivenPurchaseUnitTheItemsCategoryCouldBeEitherPhysicalGoodsAndOrDigitalGoodsOrJustDonationItemsCategoryAsDonationCannotBeCombinedWithItemsWithEitherPhysicalGoodsOrDigitalGoods = <
      any
    >'For a given \'purchase_unit\' the \'items.category\' could be either "PHYSICAL_GOODS" and/or "DIGITAL_GOODS" or just "DONATION".  \'items.category\' as "DONATION" cannot be combined with items with either "PHYSICAL_GOODS" or "DIGITAL_GOODS".',
  }
}
