/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class NOTELIGIBLEFORPNREFPROCESSING {
  'issue'?: NOTELIGIBLEFORPNREFPROCESSING.IssueEnum;
  'description'?: NOTELIGIBLEFORPNREFPROCESSING.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'NOTELIGIBLEFORPNREFPROCESSING.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'NOTELIGIBLEFORPNREFPROCESSING.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return NOTELIGIBLEFORPNREFPROCESSING.attributeTypeMap;
  }
}

export namespace NOTELIGIBLEFORPNREFPROCESSING {
  export enum IssueEnum {
    NotEligibleForPnrefProcessing = <any>'NOT_ELIGIBLE_FOR_PNREF_PROCESSING',
  }
  export enum DescriptionEnum {
    ApiCallerIsNotEnabledToProcessPaymentsWithThePnrefPleaseContactCustomerSupportToRequestPermissionsToProcessTransactionsWithPnref = <
      any
    >'API caller is not enabled to process payments with the `pnref`. Please contact customer support to request permissions to process transactions with PNREF.',
  }
}
