/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class NOTENABLEDFORAPPLEPAY {
  'issue'?: NOTENABLEDFORAPPLEPAY.IssueEnum;
  'description'?: NOTENABLEDFORAPPLEPAY.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'NOTENABLEDFORAPPLEPAY.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'NOTENABLEDFORAPPLEPAY.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return NOTENABLEDFORAPPLEPAY.attributeTypeMap;
  }
}

export namespace NOTENABLEDFORAPPLEPAY {
  export enum IssueEnum {
    NotEnabledForApplePay = <any>'NOT_ENABLED_FOR_APPLE_PAY',
  }
  export enum DescriptionEnum {
    TheApiCallerAndOrPayeeIsNotSetupToBeAbleToProcessApplePayPleaseContactYourAccountManager = <
      any
    >"The 'API caller' and/or 'payee' is not setup to be able to process apple pay. Please contact your Account Manager.",
  }
}
