/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class NOTELIGIBLEFORTOKENPROCESSING {
  'issue'?: NOTELIGIBLEFORTOKENPROCESSING.IssueEnum;
  'description'?: NOTELIGIBLEFORTOKENPROCESSING.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'NOTELIGIBLEFORTOKENPROCESSING.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'NOTELIGIBLEFORTOKENPROCESSING.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return NOTELIGIBLEFORTOKENPROCESSING.attributeTypeMap;
  }
}

export namespace NOTELIGIBLEFORTOKENPROCESSING {
  export enum IssueEnum {
    NotEligibleForTokenProcessing = <any>'NOT_ELIGIBLE_FOR_TOKEN_PROCESSING',
  }
  export enum DescriptionEnum {
    ApiCallerIsNotEnabledToProcessPaymentsWithTheSpecifiedTypeOfTokenPleaseContactCustomerSupportToRequestPermissionsToProcessTransactionsWithThisTypeOfToken = <
      any
    >'API caller is not enabled to process payments with the specified type of token. Please contact customer support to request permissions to process transactions with this type of token.',
  }
}
