/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class NOTELIGIBLEFORPAYPALTRANSACTIONIDPROCESSING {
  'issue'?: NOTELIGIBLEFORPAYPALTRANSACTIONIDPROCESSING.IssueEnum;
  'description'?: NOTELIGIBLEFORPAYPALTRANSACTIONIDPROCESSING.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'NOTELIGIBLEFORPAYPALTRANSACTIONIDPROCESSING.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'NOTELIGIBLEFORPAYPALTRANSACTIONIDPROCESSING.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return NOTELIGIBLEFORPAYPALTRANSACTIONIDPROCESSING.attributeTypeMap;
  }
}

export namespace NOTELIGIBLEFORPAYPALTRANSACTIONIDPROCESSING {
  export enum IssueEnum {
    NotEligibleForPaypalTransactionIdProcessing = <any>(
      'NOT_ELIGIBLE_FOR_PAYPAL_TRANSACTION_ID_PROCESSING'
    ),
  }
  export enum DescriptionEnum {
    ApiCallerIsNotEnableToProcessPaymentsUsingPaypalTransactionIdPleaseContactCustomerSupportToRequestPermissionsToProcessTransactionsWithPayPalTransactionId = <
      any
    >'API caller is not enable to process payments using `paypal_transaction_id`. Please contact customer support to request permissions to process transactions with PayPal transaction ID.',
  }
}
