/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class NOTENABLEDFORGOOGLEPAY {
  'issue'?: NOTENABLEDFORGOOGLEPAY.IssueEnum;
  'description'?: NOTENABLEDFORGOOGLEPAY.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'NOTENABLEDFORGOOGLEPAY.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'NOTENABLEDFORGOOGLEPAY.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return NOTENABLEDFORGOOGLEPAY.attributeTypeMap;
  }
}

export namespace NOTENABLEDFORGOOGLEPAY {
  export enum IssueEnum {
    NotEnabledForGooglePay = <any>'NOT_ENABLED_FOR_GOOGLE_PAY',
  }
  export enum DescriptionEnum {
    TheApiCallerAndOrPayeeIsNotSetupToBeAbleToProcessGooglePayPleaseContactYourAccountManager = <
      any
    >"The 'API caller' and/or 'payee' is not setup to be able to process google pay. Please contact your Account Manager.",
  }
}
