/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class NOTPATCHABLE {
  'issue'?: NOTPATCHABLE.IssueEnum;
  'description'?: NOTPATCHABLE.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'NOTPATCHABLE.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'NOTPATCHABLE.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return NOTPATCHABLE.attributeTypeMap;
  }
}

export namespace NOTPATCHABLE {
  export enum IssueEnum {
    NotPatchable = <any>'NOT_PATCHABLE',
  }
  export enum DescriptionEnum {
    CannotBePatched = <any>'Cannot be patched.',
  }
}
