/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class OrdersCapture422IssuesInner {
  'issue'?: OrdersCapture422IssuesInner.IssueEnum;
  'description'?: OrdersCapture422IssuesInner.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'OrdersCapture422IssuesInner.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'OrdersCapture422IssuesInner.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return OrdersCapture422IssuesInner.attributeTypeMap;
  }
}

export namespace OrdersCapture422IssuesInner {
  export enum IssueEnum {
    IdentifierNotFound = <any>'IDENTIFIER_NOT_FOUND',
  }
  export enum DescriptionEnum {
    SpecifiedIdentifierWasNotFoundPleaseVerifyTheCorrectIdentifierWasUsedAndTryTheRequestAgain = <
      any
    >'Specified identifier was not found. Please verify the correct identifier was used and try the request again.',
  }
}
