/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CheckoutPaymentIntent } from './checkoutPaymentIntent';
import { LinkDescription } from './linkDescription';
import { OrderStatus } from './orderStatus';
import { Payer } from './payer';
import { PaymentSourceResponse } from './paymentSourceResponse';
import { ProcessingInstruction } from './processingInstruction';
import { PurchaseUnit } from './purchaseUnit';

/**
 * The order details.
 */
export class Order {
  /**
   * The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional.<blockquote><strong>Note:</strong> The regular expression provides guidance but does not reject all invalid dates.</blockquote>
   */
  'createTime'?: string;
  /**
   * The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional.<blockquote><strong>Note:</strong> The regular expression provides guidance but does not reject all invalid dates.</blockquote>
   */
  'updateTime'?: string;
  /**
   * The ID of the order.
   */
  'id'?: string;
  'paymentSource'?: PaymentSourceResponse;
  'intent'?: CheckoutPaymentIntent;
  'processingInstruction'?: ProcessingInstruction;
  'payer'?: Payer;
  /**
   * An array of purchase units. Each purchase unit establishes a contract between a customer and merchant. Each purchase unit represents either a full or partial order that the customer intends to purchase from the merchant.
   */
  'purchaseUnits'?: Array<PurchaseUnit>;
  'status'?: OrderStatus;
  /**
   * An array of request-related HATEOAS links. To complete payer approval, use the `approve` link to redirect the payer. The API caller has 3 hours (default setting, this which can be changed by your account manager to 24/48/72 hours to accommodate your use case) from the time the order is created, to redirect your payer. Once redirected, the API caller has 3 hours for the payer to approve the order and either authorize or capture the order. If you are not using the PayPal JavaScript SDK to initiate PayPal Checkout (in context) ensure that you include `application_context.return_url` is specified or you will get \"We\'re sorry, Things don\'t appear to be working at the moment\" after the payer approves the payment.
   */
  'links'?: Array<LinkDescription>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'createTime',
      baseName: 'create_time',
      type: 'string',
    },
    {
      name: 'updateTime',
      baseName: 'update_time',
      type: 'string',
    },
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
    },
    {
      name: 'paymentSource',
      baseName: 'payment_source',
      type: 'PaymentSourceResponse',
    },
    {
      name: 'intent',
      baseName: 'intent',
      type: 'CheckoutPaymentIntent',
    },
    {
      name: 'processingInstruction',
      baseName: 'processing_instruction',
      type: 'ProcessingInstruction',
    },
    {
      name: 'payer',
      baseName: 'payer',
      type: 'Payer',
    },
    {
      name: 'purchaseUnits',
      baseName: 'purchase_units',
      type: 'Array<PurchaseUnit>',
    },
    {
      name: 'status',
      baseName: 'status',
      type: 'OrderStatus',
    },
    {
      name: 'links',
      baseName: 'links',
      type: 'Array<LinkDescription>',
    },
  ];

  static getAttributeTypeMap() {
    return Order.attributeTypeMap;
  }
}

export namespace Order {}
