/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class ORDEREXPIRED {
  'issue'?: ORDEREXPIRED.IssueEnum;
  'description'?: ORDEREXPIRED.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'ORDEREXPIRED.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'ORDEREXPIRED.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return ORDEREXPIRED.attributeTypeMap;
  }
}

export namespace ORDEREXPIRED {
  export enum IssueEnum {
    OrderExpired = <any>'ORDER_EXPIRED',
  }
  export enum DescriptionEnum {
    OrderIsExpiredAndHenceCannotBeAuthorizedPleaseContactCustomerSupportIfYouNeedToIncreaseYourOrderValidityPeriod = <
      any
    >'Order is expired and hence cannot be authorized. Please contact Customer Support if you need to increase your order validity period.',
  }
}
