/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class OrdersAuthorize400IssuesInner {
  'issue'?: OrdersAuthorize400IssuesInner.IssueEnum;
  'description'?: OrdersAuthorize400IssuesInner.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'OrdersAuthorize400IssuesInner.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'OrdersAuthorize400IssuesInner.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return OrdersAuthorize400IssuesInner.attributeTypeMap;
  }
}

export namespace OrdersAuthorize400IssuesInner {
  export enum IssueEnum {
    MalformedRequestJson = <any>'MALFORMED_REQUEST_JSON',
  }
  export enum DescriptionEnum {
    TheRequestJsonIsNotWellFormed = <any>'The request JSON is not well formed.',
  }
}
