/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class PATCHPATHREQUIRED1 {
  'issue'?: PATCHPATHREQUIRED1.IssueEnum;
  'description'?: PATCHPATHREQUIRED1.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'PATCHPATHREQUIRED1.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'PATCHPATHREQUIRED1.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return PATCHPATHREQUIRED1.attributeTypeMap;
  }
}

export namespace PATCHPATHREQUIRED1 {
  export enum IssueEnum {
    PatchPathRequired = <any>'PATCH_PATH_REQUIRED',
  }
  export enum DescriptionEnum {
    SpecifyAValueForTheFieldInWhichTheOperationNeedsToBePerformed = <any>(
      'Specify a `value` for the field in which the operation needs to be performed.'
    ),
  }
}
