/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class PATCHVALUEREQUIRED1 {
  'issue'?: PATCHVALUEREQUIRED1.IssueEnum;
  'description'?: PATCHVALUEREQUIRED1.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'PATCHVALUEREQUIRED1.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'PATCHVALUEREQUIRED1.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return PATCHVALUEREQUIRED1.attributeTypeMap;
  }
}

export namespace PATCHVALUEREQUIRED1 {
  export enum IssueEnum {
    PatchValueRequired = <any>'PATCH_VALUE_REQUIRED',
  }
  export enum DescriptionEnum {
    SpecifyAValueForTheFieldBeingPatched = <any>(
      'Specify a `value` for the field being patched.'
    ),
  }
}
