/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class PAYEEACCOUNTLOCKEDORCLOSED {
  'issue'?: PAYEEACCOUNTLOCKEDORCLOSED.IssueEnum;
  'description'?: PAYEEACCOUNTLOCKEDORCLOSED.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'PAYEEACCOUNTLOCKEDORCLOSED.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'PAYEEACCOUNTLOCKEDORCLOSED.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return PAYEEACCOUNTLOCKEDORCLOSED.attributeTypeMap;
  }
}

export namespace PAYEEACCOUNTLOCKEDORCLOSED {
  export enum IssueEnum {
    PayeeAccountLockedOrClosed = <any>'PAYEE_ACCOUNT_LOCKED_OR_CLOSED',
  }
  export enum DescriptionEnum {
    TheMerchantAccountIsLockedOrClosed = <any>(
      'The merchant account is locked or closed.'
    ),
  }
}
