/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class PAYEEACCOUNTINVALID {
  'issue'?: PAYEEACCOUNTINVALID.IssueEnum;
  'description'?: PAYEEACCOUNTINVALID.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'PAYEEACCOUNTINVALID.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'PAYEEACCOUNTINVALID.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return PAYEEACCOUNTINVALID.attributeTypeMap;
  }
}

export namespace PAYEEACCOUNTINVALID {
  export enum IssueEnum {
    PayeeAccountInvalid = <any>'PAYEE_ACCOUNT_INVALID',
  }
  export enum DescriptionEnum {
    PayeeAccountSpecifiedIsInvalidPleaseCheckThePayeeEmailAddressOrPayeeMerchantIdSpecifiedAndTryAgainEnsureThatEitherPayeeMerchantIdOrPayeeEmailAddressIsSpecified = <
      any
    >'Payee account specified is invalid. Please check the `payee.email_address` or `payee.merchant_id` specified and try again. Ensure that either  `payee.merchant_id` or `payee.email_address` is specified.',
  }
}
