/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApplePayRequest } from './applePayRequest';
import { BancontactRequest } from './bancontactRequest';
import { BlikRequest } from './blikRequest';
import { CardRequest } from './cardRequest';
import { EpsRequest } from './epsRequest';
import { GiropayRequest } from './giropayRequest';
import { IdealRequest } from './idealRequest';
import { MybankRequest } from './mybankRequest';
import { P24Request } from './p24Request';
import { PaypalWallet } from './paypalWallet';
import { SofortRequest } from './sofortRequest';
import { Token } from './token';
import { TrustlyRequest } from './trustlyRequest';
import { VenmoWalletRequest } from './venmoWalletRequest';

/**
 * The payment source definition.
 */
export class PaymentSource {
  'card'?: CardRequest;
  'token'?: Token;
  'paypal'?: PaypalWallet;
  'bancontact'?: BancontactRequest;
  'blik'?: BlikRequest;
  'eps'?: EpsRequest;
  'giropay'?: GiropayRequest;
  'ideal'?: IdealRequest;
  'mybank'?: MybankRequest;
  'p24'?: P24Request;
  'sofort'?: SofortRequest;
  'trustly'?: TrustlyRequest;
  'applePay'?: ApplePayRequest;
  'googlePay'?: any | null;
  'venmo'?: VenmoWalletRequest;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'card',
      baseName: 'card',
      type: 'CardRequest',
    },
    {
      name: 'token',
      baseName: 'token',
      type: 'Token',
    },
    {
      name: 'paypal',
      baseName: 'paypal',
      type: 'PaypalWallet',
    },
    {
      name: 'bancontact',
      baseName: 'bancontact',
      type: 'BancontactRequest',
    },
    {
      name: 'blik',
      baseName: 'blik',
      type: 'BlikRequest',
    },
    {
      name: 'eps',
      baseName: 'eps',
      type: 'EpsRequest',
    },
    {
      name: 'giropay',
      baseName: 'giropay',
      type: 'GiropayRequest',
    },
    {
      name: 'ideal',
      baseName: 'ideal',
      type: 'IdealRequest',
    },
    {
      name: 'mybank',
      baseName: 'mybank',
      type: 'MybankRequest',
    },
    {
      name: 'p24',
      baseName: 'p24',
      type: 'P24Request',
    },
    {
      name: 'sofort',
      baseName: 'sofort',
      type: 'SofortRequest',
    },
    {
      name: 'trustly',
      baseName: 'trustly',
      type: 'TrustlyRequest',
    },
    {
      name: 'applePay',
      baseName: 'apple_pay',
      type: 'ApplePayRequest',
    },
    {
      name: 'googlePay',
      baseName: 'google_pay',
      type: 'any',
    },
    {
      name: 'venmo',
      baseName: 'venmo',
      type: 'VenmoWalletRequest',
    },
  ];

  static getAttributeTypeMap() {
    return PaymentSource.attributeTypeMap;
  }
}
