/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CobrandedCard } from './cobrandedCard';
import { VaultResponse } from './vaultResponse';

/**
 * Additional attributes associated with the use of a PayPal Wallet.
 */
export class PaypalWalletAttributesResponse {
  'vault'?: VaultResponse;
  /**
   * An array of merchant cobranded cards used by buyer to complete an order. This array will be present if a merchant has onboarded their cobranded card with PayPal and provided corresponding label(s).
   */
  'cobrandedCards'?: Array<CobrandedCard>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'vault',
      baseName: 'vault',
      type: 'VaultResponse',
    },
    {
      name: 'cobrandedCards',
      baseName: 'cobranded_cards',
      type: 'Array<CobrandedCard>',
    },
  ];

  static getAttributeTypeMap() {
    return PaypalWalletAttributesResponse.attributeTypeMap;
  }
}
