/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class PLATFORMFEEPAYEECANNOTBESAMEASPAYER {
  'issue'?: PLATFORMFEEPAYEECANNOTBESAMEASPAYER.IssueEnum;
  'description'?: PLATFORMFEEPAYEECANNOTBESAMEASPAYER.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'PLATFORMFEEPAYEECANNOTBESAMEASPAYER.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'PLATFORMFEEPAYEECANNOTBESAMEASPAYER.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return PLATFORMFEEPAYEECANNOTBESAMEASPAYER.attributeTypeMap;
  }
}

export namespace PLATFORMFEEPAYEECANNOTBESAMEASPAYER {
  export enum IssueEnum {
    PlatformFeePayeeCannotBeSameAsPayer = <any>(
      'PLATFORM_FEE_PAYEE_CANNOT_BE_SAME_AS_PAYER'
    ),
  }
  export enum DescriptionEnum {
    ThePayerCannotPayThemselvesTheRecipientAccountOfThePlatformFeesMustBeDifferentFromThePayerAccount = <
      any
    >'The payer cannot pay themselves. The recipient account of the platform fees must be different from the payer account.',
  }
}
