/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class PLATFORMFEESNOTSUPPORTED {
  'issue'?: PLATFORMFEESNOTSUPPORTED.IssueEnum;
  'description'?: PLATFORMFEESNOTSUPPORTED.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'PLATFORMFEESNOTSUPPORTED.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'PLATFORMFEESNOTSUPPORTED.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return PLATFORMFEESNOTSUPPORTED.attributeTypeMap;
  }
}

export namespace PLATFORMFEESNOTSUPPORTED {
  export enum IssueEnum {
    PlatformFeesNotSupported = <any>'PLATFORM_FEES_NOT_SUPPORTED',
  }
  export enum DescriptionEnum {
    TheApiCallerIsNotEnabledToProcessTransactionsBySpecifyingPlatformFeesPleaseWorkWithYourPayPalAccountManagerToEnableThisOptionForYourAccount = <
      any
    >"The API Caller is not enabled to process transactions by specifying 'platform_fees'. Please work with your PayPal Account Manager to enable this option for your account.",
  }
}
