/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class PREFERREDSHIPPINGOPTIONAMOUNTMISMATCH {
  'issue'?: PREFERREDSHIPPINGOPTIONAMOUNTMISMATCH.IssueEnum;
  'description'?: PREFERREDSHIPPINGOPTIONAMOUNTMISMATCH.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'PREFERREDSHIPPINGOPTIONAMOUNTMISMATCH.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'PREFERREDSHIPPINGOPTIONAMOUNTMISMATCH.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return PREFERREDSHIPPINGOPTIONAMOUNTMISMATCH.attributeTypeMap;
  }
}

export namespace PREFERREDSHIPPINGOPTIONAMOUNTMISMATCH {
  export enum IssueEnum {
    PreferredShippingOptionAmountMismatch = <any>(
      'PREFERRED_SHIPPING_OPTION_AMOUNT_MISMATCH'
    ),
  }
  export enum DescriptionEnum {
    TheAmountProvidedInThePreferredShippingOptionShouldMatchTheAmountProvidedInAmountBreakdown = <
      any
    >'The amount provided in the preferred shipping option should match the amount provided in amount breakdown',
  }
}
