/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class PREVIOUSTRANSACTIONREFERENCEHASCHARGEBACK {
  'issue'?: PREVIOUSTRANSACTIONREFERENCEHASCHARGEBACK.IssueEnum;
  'description'?: PREVIOUSTRANSACTIONREFERENCEHASCHARGEBACK.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'PREVIOUSTRANSACTIONREFERENCEHASCHARGEBACK.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'PREVIOUSTRANSACTIONREFERENCEHASCHARGEBACK.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return PREVIOUSTRANSACTIONREFERENCEHASCHARGEBACK.attributeTypeMap;
  }
}

export namespace PREVIOUSTRANSACTIONREFERENCEHASCHARGEBACK {
  export enum IssueEnum {
    PreviousTransactionReferenceHasChargeback = <any>(
      'PREVIOUS_TRANSACTION_REFERENCE_HAS_CHARGEBACK'
    ),
  }
  export enum DescriptionEnum {
    TheCaptureReferencedByPreviousTransactionReferenceHasAChargebackAndHenceCannotBeUsedForThisOrderPleaseUseAPreviousTransactionReferenceWhichDoesNotHaveAChargeback = <
      any
    >'The capture referenced by `previous_transaction_reference` has a chargeback and hence cannot be used for this order. Please use a `previous_transaction_reference` which does not have a chargeback.',
  }
}
