/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The processor response information for payment requests, such as direct credit card transactions.
 */
export class ProcessorResponse {
  /**
   * The address verification code for Visa, Discover, Mastercard, or American Express transactions.
   */
  'avsCode'?: ProcessorResponse.AvsCodeEnum;
  /**
   * The card verification value code for for Visa, Discover, Mastercard, or American Express.
   */
  'cvvCode'?: ProcessorResponse.CvvCodeEnum;
  /**
   * Processor response code for the non-PayPal payment processor errors.
   */
  'responseCode'?: ProcessorResponse.ResponseCodeEnum;
  /**
   * The declined payment transactions might have payment advice codes. The card networks, like Visa and Mastercard, return payment advice codes.
   */
  'paymentAdviceCode'?: ProcessorResponse.PaymentAdviceCodeEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'avsCode',
      baseName: 'avs_code',
      type: 'ProcessorResponse.AvsCodeEnum',
    },
    {
      name: 'cvvCode',
      baseName: 'cvv_code',
      type: 'ProcessorResponse.CvvCodeEnum',
    },
    {
      name: 'responseCode',
      baseName: 'response_code',
      type: 'ProcessorResponse.ResponseCodeEnum',
    },
    {
      name: 'paymentAdviceCode',
      baseName: 'payment_advice_code',
      type: 'ProcessorResponse.PaymentAdviceCodeEnum',
    },
  ];

  static getAttributeTypeMap() {
    return ProcessorResponse.attributeTypeMap;
  }
}

export namespace ProcessorResponse {
  export enum AvsCodeEnum {
    A = <any>'A',
    B = <any>'B',
    C = <any>'C',
    D = <any>'D',
    E = <any>'E',
    F = <any>'F',
    G = <any>'G',
    I = <any>'I',
    M = <any>'M',
    N = <any>'N',
    P = <any>'P',
    R = <any>'R',
    S = <any>'S',
    U = <any>'U',
    W = <any>'W',
    X = <any>'X',
    Y = <any>'Y',
    Z = <any>'Z',
    Null = <any>'Null',
    _0 = <any>'0',
    _1 = <any>'1',
    _2 = <any>'2',
    _3 = <any>'3',
    _4 = <any>'4',
  }
  export enum CvvCodeEnum {
    E = <any>'E',
    I = <any>'I',
    M = <any>'M',
    N = <any>'N',
    P = <any>'P',
    S = <any>'S',
    U = <any>'U',
    X = <any>'X',
    AllOthers = <any>'All others',
    _0 = <any>'0',
    _1 = <any>'1',
    _2 = <any>'2',
    _3 = <any>'3',
    _4 = <any>'4',
  }
  export enum ResponseCodeEnum {
    _0000 = <any>'0000',
    _00N7 = <any>'00N7',
    _0100 = <any>'0100',
    _0390 = <any>'0390',
    _0500 = <any>'0500',
    _0580 = <any>'0580',
    _0800 = <any>'0800',
    _0880 = <any>'0880',
    _0890 = <any>'0890',
    _0960 = <any>'0960',
    _0R00 = <any>'0R00',
    _1000 = <any>'1000',
    _10Br = <any>'10BR',
    _1300 = <any>'1300',
    _1310 = <any>'1310',
    _1312 = <any>'1312',
    _1317 = <any>'1317',
    _1320 = <any>'1320',
    _1330 = <any>'1330',
    _1335 = <any>'1335',
    _1340 = <any>'1340',
    _1350 = <any>'1350',
    _1352 = <any>'1352',
    _1360 = <any>'1360',
    _1370 = <any>'1370',
    _1380 = <any>'1380',
    _1382 = <any>'1382',
    _1384 = <any>'1384',
    _1390 = <any>'1390',
    _1393 = <any>'1393',
    _5100 = <any>'5100',
    _5110 = <any>'5110',
    _5120 = <any>'5120',
    _5130 = <any>'5130',
    _5135 = <any>'5135',
    _5140 = <any>'5140',
    _5150 = <any>'5150',
    _5160 = <any>'5160',
    _5170 = <any>'5170',
    _5180 = <any>'5180',
    _5190 = <any>'5190',
    _5200 = <any>'5200',
    _5210 = <any>'5210',
    _5400 = <any>'5400',
    _5500 = <any>'5500',
    _5650 = <any>'5650',
    _5700 = <any>'5700',
    _5710 = <any>'5710',
    _5800 = <any>'5800',
    _5900 = <any>'5900',
    _5910 = <any>'5910',
    _5920 = <any>'5920',
    _5930 = <any>'5930',
    _5950 = <any>'5950',
    _6300 = <any>'6300',
    _7600 = <any>'7600',
    _7700 = <any>'7700',
    _7710 = <any>'7710',
    _7800 = <any>'7800',
    _7900 = <any>'7900',
    _8000 = <any>'8000',
    _8010 = <any>'8010',
    _8020 = <any>'8020',
    _8030 = <any>'8030',
    _8100 = <any>'8100',
    _8110 = <any>'8110',
    _8220 = <any>'8220',
    _9100 = <any>'9100',
    _9500 = <any>'9500',
    _9510 = <any>'9510',
    _9520 = <any>'9520',
    _9530 = <any>'9530',
    _9540 = <any>'9540',
    _9600 = <any>'9600',
    Pcnr = <any>'PCNR',
    Pcvv = <any>'PCVV',
    Pp06 = <any>'PP06',
    Pprn = <any>'PPRN',
    Ppad = <any>'PPAD',
    Ppab = <any>'PPAB',
    Ppae = <any>'PPAE',
    Ppag = <any>'PPAG',
    Ppai = <any>'PPAI',
    Ppar = <any>'PPAR',
    Ppau = <any>'PPAU',
    Ppav = <any>'PPAV',
    Ppax = <any>'PPAX',
    Ppbg = <any>'PPBG',
    Ppc2 = <any>'PPC2',
    Ppce = <any>'PPCE',
    Ppco = <any>'PPCO',
    Ppcr = <any>'PPCR',
    Ppct = <any>'PPCT',
    Ppcu = <any>'PPCU',
    Ppd3 = <any>'PPD3',
    Ppdc = <any>'PPDC',
    Ppdi = <any>'PPDI',
    Ppdv = <any>'PPDV',
    Ppdt = <any>'PPDT',
    Ppef = <any>'PPEF',
    Ppel = <any>'PPEL',
    Pper = <any>'PPER',
    Ppex = <any>'PPEX',
    Ppfe = <any>'PPFE',
    Ppfi = <any>'PPFI',
    Ppfr = <any>'PPFR',
    Ppfv = <any>'PPFV',
    Ppgr = <any>'PPGR',
    Pph1 = <any>'PPH1',
    Ppif = <any>'PPIF',
    Ppii = <any>'PPII',
    Ppim = <any>'PPIM',
    Ppit = <any>'PPIT',
    Pplr = <any>'PPLR',
    Ppls = <any>'PPLS',
    Ppmb = <any>'PPMB',
    Ppmc = <any>'PPMC',
    Ppmd = <any>'PPMD',
    Ppnc = <any>'PPNC',
    Ppnl = <any>'PPNL',
    Ppnm = <any>'PPNM',
    Ppnt = <any>'PPNT',
    Ppph = <any>'PPPH',
    Pppi = <any>'PPPI',
    Pppm = <any>'PPPM',
    Ppqc = <any>'PPQC',
    Ppre = <any>'PPRE',
    Pprf = <any>'PPRF',
    Pprr = <any>'PPRR',
    Pps0 = <any>'PPS0',
    Pps1 = <any>'PPS1',
    Pps2 = <any>'PPS2',
    Pps3 = <any>'PPS3',
    Pps4 = <any>'PPS4',
    Pps5 = <any>'PPS5',
    Pps6 = <any>'PPS6',
    Ppsc = <any>'PPSC',
    Ppsd = <any>'PPSD',
    Ppse = <any>'PPSE',
    Ppte = <any>'PPTE',
    Pptf = <any>'PPTF',
    Ppti = <any>'PPTI',
    Pptr = <any>'PPTR',
    Pptt = <any>'PPTT',
    Pptv = <any>'PPTV',
    Ppua = <any>'PPUA',
    Ppuc = <any>'PPUC',
    Ppue = <any>'PPUE',
    Ppui = <any>'PPUI',
    Ppup = <any>'PPUP',
    Ppur = <any>'PPUR',
    Ppvc = <any>'PPVC',
    Ppve = <any>'PPVE',
    Ppvt = <any>'PPVT',
  }
  export enum PaymentAdviceCodeEnum {
    _01 = <any>'01',
    _02 = <any>'02',
    _03 = <any>'03',
    _21 = <any>'21',
  }
}
