/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class REDIRECTPAYERFORALTERNATEFUNDING {
  'issue'?: REDIRECTPAYERFORALTERNATEFUNDING.IssueEnum;
  'description'?: REDIRECTPAYERFORALTERNATEFUNDING.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'REDIRECTPAYERFORALTERNATEFUNDING.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'REDIRECTPAYERFORALTERNATEFUNDING.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return REDIRECTPAYERFORALTERNATEFUNDING.attributeTypeMap;
  }
}

export namespace REDIRECTPAYERFORALTERNATEFUNDING {
  export enum IssueEnum {
    RedirectPayerForAlternateFunding = <any>(
      'REDIRECT_PAYER_FOR_ALTERNATE_FUNDING'
    ),
  }
  export enum DescriptionEnum {
    TransactionFailedRedirectThePayerToSelectAnotherFundingSource = <any>(
      'Transaction failed. Redirect the payer to select another funding source.'
    ),
  }
}
