/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class REQUIREDPARAMETERFORCUSTOMERINITIATEDPAYMENT {
  'issue'?: REQUIREDPARAMETERFORCUSTOMERINITIATEDPAYMENT.IssueEnum;
  'description'?: REQUIREDPARAMETERFORCUSTOMERINITIATEDPAYMENT.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'REQUIREDPARAMETERFORCUSTOMERINITIATEDPAYMENT.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'REQUIREDPARAMETERFORCUSTOMERINITIATEDPAYMENT.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return REQUIREDPARAMETERFORCUSTOMERINITIATEDPAYMENT.attributeTypeMap;
  }
}

export namespace REQUIREDPARAMETERFORCUSTOMERINITIATEDPAYMENT {
  export enum IssueEnum {
    RequiredParameterForCustomerInitiatedPayment = <any>(
      'REQUIRED_PARAMETER_FOR_CUSTOMER_INITIATED_PAYMENT'
    ),
  }
  export enum DescriptionEnum {
    ThisParameterIsRequiredWhenTheCustomerIsPresentIfTheCustomerIsNotPresentIndicateSoBySendingPaymentInitiatorMerchantForDetailsSeeAHrefhttpsDeveloperPaypalComDocsApiOrdersV2DefinitionCardStoredCredentialStoredCredentialA = <
      any
    >'This parameter is required when the customer is present. If the customer is not present, indicate so by sending payment_initiator=`MERCHANT`. For details, see <a href="https://developer.paypal.com/docs/api/orders/v2/#definition-card_stored_credential">Stored Credential</a>.',
  }
}
