/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class REQUIREDPARAMETERFORPAYMENTSOURCE {
  'issue'?: REQUIREDPARAMETERFORPAYMENTSOURCE.IssueEnum;
  'description'?: REQUIREDPARAMETERFORPAYMENTSOURCE.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'REQUIREDPARAMETERFORPAYMENTSOURCE.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'REQUIREDPARAMETERFORPAYMENTSOURCE.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return REQUIREDPARAMETERFORPAYMENTSOURCE.attributeTypeMap;
  }
}

export namespace REQUIREDPARAMETERFORPAYMENTSOURCE {
  export enum IssueEnum {
    RequiredParameterForPaymentSource = <any>(
      'REQUIRED_PARAMETER_FOR_PAYMENT_SOURCE'
    ),
  }
  export enum DescriptionEnum {
    TheParameterIsRequiredForProvidedPaymentSource = <any>(
      'The parameter is required for provided payment source.'
    ),
  }
}
