/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AddressPortable } from './addressPortable';
import { Name } from './name';
import { Tracker } from './tracker';

/**
 * The order shipping details.
 */
export class ShippingWithTrackingDetails {
  'name'?: Name;
  /**
   * The method by which the payer wants to get their items from the payee e.g shipping, in-person pickup. Either type or options but not both may be present.
   */
  'type'?: ShippingWithTrackingDetails.TypeEnum;
  'address'?: AddressPortable;
  /**
   * An array of trackers for a transaction.
   */
  'trackers'?: Array<Tracker>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'name',
      baseName: 'name',
      type: 'Name',
    },
    {
      name: 'type',
      baseName: 'type',
      type: 'ShippingWithTrackingDetails.TypeEnum',
    },
    {
      name: 'address',
      baseName: 'address',
      type: 'AddressPortable',
    },
    {
      name: 'trackers',
      baseName: 'trackers',
      type: 'Array<Tracker>',
    },
  ];

  static getAttributeTypeMap() {
    return ShippingWithTrackingDetails.attributeTypeMap;
  }
}

export namespace ShippingWithTrackingDetails {
  export enum TypeEnum {
    Shipping = <any>'SHIPPING',
    PickupInPerson = <any>'PICKUP_IN_PERSON',
  }
}
