/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class SHIPPINGTYPENOTSUPPORTEDFORCLIENT {
  'issue'?: SHIPPINGTYPENOTSUPPORTEDFORCLIENT.IssueEnum;
  'description'?: SHIPPINGTYPENOTSUPPORTEDFORCLIENT.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'SHIPPINGTYPENOTSUPPORTEDFORCLIENT.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'SHIPPINGTYPENOTSUPPORTEDFORCLIENT.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return SHIPPINGTYPENOTSUPPORTEDFORCLIENT.attributeTypeMap;
  }
}

export namespace SHIPPINGTYPENOTSUPPORTEDFORCLIENT {
  export enum IssueEnum {
    ShippingTypeNotSupportedForClient = <any>(
      'SHIPPING_TYPE_NOT_SUPPORTED_FOR_CLIENT'
    ),
  }
  export enum DescriptionEnum {
    TheApiCallerAccountIsNotSetupToBeAbleToSupportAShippingTypePickupInPersonThisFeatureIsOnlySupportedForAHrefhttpsWwwPaypalComUsBusinessPlatformsAndMarketplacesPayPalCommercePlatformForPlatformsAndMarketplacesA = <
      any
    >'The API Caller account is not setup to be able to support a `shipping.type`=`PICKUP_IN_PERSON`. This feature is only supported for <a href="https://www.paypal.com/us/business/platforms-and-marketplaces">PayPal Commerce Platform for Platforms and Marketplaces</a>.',
  }
}
