/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class SHIPPINGADDRESSINVALID {
  'issue'?: SHIPPINGADDRESSINVALID.IssueEnum;
  'description'?: SHIPPINGADDRESSINVALID.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'SHIPPINGADDRESSINVALID.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'SHIPPINGADDRESSINVALID.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return SHIPPINGADDRESSINVALID.attributeTypeMap;
  }
}

export namespace SHIPPINGADDRESSINVALID {
  export enum IssueEnum {
    ShippingAddressInvalid = <any>'SHIPPING_ADDRESS_INVALID',
  }
  export enum DescriptionEnum {
    ProvidedShippingAddressIsInvalid = <any>(
      'Provided shipping address is invalid.'
    ),
  }
}
