/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The tax ID of the customer. The customer is also known as the payer. Both `tax_id` and `tax_id_type` are required.
 */
export class TaxInfo {
  /**
   * The customer\'s tax ID value.
   */
  'taxId': string;
  /**
   * The customer\'s tax ID type.
   */
  'taxIdType': TaxInfo.TaxIdTypeEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'taxId',
      baseName: 'tax_id',
      type: 'string',
    },
    {
      name: 'taxIdType',
      baseName: 'tax_id_type',
      type: 'TaxInfo.TaxIdTypeEnum',
    },
  ];

  static getAttributeTypeMap() {
    return TaxInfo.attributeTypeMap;
  }
}

export namespace TaxInfo {
  export enum TaxIdTypeEnum {
    Cpf = <any>'BR_CPF',
    Cnpj = <any>'BR_CNPJ',
  }
}
