/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class TOKENEXPIRED {
  'issue'?: TOKENEXPIRED.IssueEnum;
  'description'?: TOKENEXPIRED.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'TOKENEXPIRED.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'TOKENEXPIRED.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return TOKENEXPIRED.attributeTypeMap;
  }
}

export namespace TOKENEXPIRED {
  export enum IssueEnum {
    TokenExpired = <any>'TOKEN_EXPIRED',
  }
  export enum DescriptionEnum {
    TheTokenIsExpiredAndCannotBeUsedForPayment = <any>(
      'The token is expired and cannot be used for payment.'
    ),
  }
}
