/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class TOKENIDNOTFOUND {
  'issue'?: TOKENIDNOTFOUND.IssueEnum;
  'description'?: TOKENIDNOTFOUND.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'TOKENIDNOTFOUND.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'TOKENIDNOTFOUND.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return TOKENIDNOTFOUND.attributeTypeMap;
  }
}

export namespace TOKENIDNOTFOUND {
  export enum IssueEnum {
    TokenIdNotFound = <any>'TOKEN_ID_NOT_FOUND',
  }
  export enum DescriptionEnum {
    SpecifiedTokenWasNotFoundVerifyTheTokenAndTryTheRequestAgain = <any>(
      'Specified token was not found. Verify the token and try the request again.'
    ),
  }
}
