/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class UNSUPPORTEDSHIPPINGTYPE {
  'issue'?: UNSUPPORTEDSHIPPINGTYPE.IssueEnum;
  'description'?: UNSUPPORTEDSHIPPINGTYPE.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'UNSUPPORTEDSHIPPINGTYPE.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'UNSUPPORTEDSHIPPINGTYPE.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return UNSUPPORTEDSHIPPINGTYPE.attributeTypeMap;
  }
}

export namespace UNSUPPORTEDSHIPPINGTYPE {
  export enum IssueEnum {
    UnsupportedShippingType = <any>'UNSUPPORTED_SHIPPING_TYPE',
  }
  export enum DescriptionEnum {
    TheProvidedShippingTypeIsOnlySupportedForApplicationContextShippingPreferenceSetProvidedAddressOrNoShipping = <
      any
    >'The provided `shipping.type` is only supported for `application_context.shipping_preference`=`SET_PROVIDED_ADDRESS` or `NO_SHIPPING`.',
  }
}
