/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class UNSUPPORTEDINTENTFORPAYMENTSOURCE {
  'issue'?: UNSUPPORTEDINTENTFORPAYMENTSOURCE.IssueEnum;
  'description'?: UNSUPPORTEDINTENTFORPAYMENTSOURCE.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'UNSUPPORTEDINTENTFORPAYMENTSOURCE.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'UNSUPPORTEDINTENTFORPAYMENTSOURCE.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return UNSUPPORTEDINTENTFORPAYMENTSOURCE.attributeTypeMap;
  }
}

export namespace UNSUPPORTEDINTENTFORPAYMENTSOURCE {
  export enum IssueEnum {
    UnsupportedIntentForPaymentSource = <any>(
      'UNSUPPORTED_INTENT_FOR_PAYMENT_SOURCE'
    ),
  }
  export enum DescriptionEnum {
    IntentAuthorizeIsNotSupportedForTheSpecifiedPaymentSourceOnlyIntentCaptureIsSupported = <
      any
    >'`intent=AUTHORIZE` is not supported for the specified payment_source. Only `intent=CAPTURE` is supported.',
  }
}
