/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VenmoWalletAttributes } from './venmoWalletAttributes';
import { VenmoWalletExperienceContext } from './venmoWalletExperienceContext';

/**
 * Information needed to pay using Venmo.
 */
export class VenmoWalletRequest {
  /**
   * The PayPal-generated ID for the vaulted payment source. This ID should be stored on the merchant\'s server so the saved payment source can be used for future transactions.
   */
  'vaultId'?: string;
  /**
   * The internationalized email address.<blockquote><strong>Note:</strong> Up to 64 characters are allowed before and 255 characters are allowed after the <code>@</code> sign. However, the generally accepted maximum length for an email address is 254 characters. The pattern verifies that an unquoted <code>@</code> sign exists.</blockquote>
   */
  'emailAddress'?: string;
  'experienceContext'?: VenmoWalletExperienceContext;
  'attributes'?: VenmoWalletAttributes;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'vaultId',
      baseName: 'vault_id',
      type: 'string',
    },
    {
      name: 'emailAddress',
      baseName: 'email_address',
      type: 'string',
    },
    {
      name: 'experienceContext',
      baseName: 'experience_context',
      type: 'VenmoWalletExperienceContext',
    },
    {
      name: 'attributes',
      baseName: 'attributes',
      type: 'VenmoWalletAttributes',
    },
  ];

  static getAttributeTypeMap() {
    return VenmoWalletRequest.attributeTypeMap;
  }
}
