import { SettingsFormDataType } from '../../types/types';

export const DEFAULT_SETTINGS: SettingsFormDataType = {
  email: 'pat.brandt@email.com',
  acceptPayPal: true,
  acceptPayLater: true,
  acceptVenmo: true,
  acceptLocal: true,
  acceptCredit: false,
  buttonPaymentPage: true,
  buttonCartPage: true,
  buttonDetailPage: true,
  buttonShippingPage: true,
  buttonShape: 'rectangle',
  buttonTagline: false,
  buttonColor: 'blue',
  buttonLabel: 'pay',
  payLaterMessagingType: 'text',
  payLaterMessageCartPage: true,
  payLaterMessagePaymentPage: true,
  payLaterMessageCategoryPage: true,
  payLaterMessageDetailsPage: true,
  payLaterMessageHomePage: true,
  payLaterMessageTextLogoType: 'primary',
  payLaterMessageTextLogoPosition: 'left',
  payLaterMessageTextColor: 'black',
  payLaterMessageTextSize: '12',
  payLaterMessageTextAlign: 'left',
  payLaterMessageFlexColor: 'blue',
  payLaterMessageFlexRatio: '1x1',
  threeDSOption: 'SCA_WHEN_REQUIRED',
  payPalIntent: 'Capture',
  partnerAttributionId: '',
  ratePayBrandName: { de: '' },
  ratePayLogoUrl: { de: '' },
  ratePayCustomerServiceInstructions: { de: '' },
  paymentDescription: { en: '' },
};
