/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class APPLEPAYAMOUNTMISMATCH {
  'issue'?: APPLEPAYAMOUNTMISMATCH.IssueEnum;
  'description'?: APPLEPAYAMOUNTMISMATCH.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'APPLEPAYAMOUNTMISMATCH.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'APPLEPAYAMOUNTMISMATCH.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return APPLEPAYAMOUNTMISMATCH.attributeTypeMap;
  }
}

export namespace APPLEPAYAMOUNTMISMATCH {
  export enum IssueEnum {
    ApplePayAmountMismatch = <any>'APPLE_PAY_AMOUNT_MISMATCH',
  }
  export enum DescriptionEnum {
    TheAmountSpecifiedInTheOrderShouldMatchTheAmountThatWasViewedAndAuthorizedByThePayerBuyerOnApplePayIfTheAmountHasChangedPleaseRedirectTheBuyerToAuthorizeTheOrderAgainViaApplePay = <
      any
    >"The 'amount' specified in the Order should match the amount that was viewed and authorized by the payer/buyer on Apple Pay. If the amount has changed, please redirect the buyer to authorize the order again via Apple Pay.",
  }
}
