/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class AUTHORIZATIONAMOUNTEXCEEDED {
  'issue'?: AUTHORIZATIONAMOUNTEXCEEDED.IssueEnum;
  'description'?: AUTHORIZATIONAMOUNTEXCEEDED.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'AUTHORIZATIONAMOUNTEXCEEDED.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'AUTHORIZATIONAMOUNTEXCEEDED.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return AUTHORIZATIONAMOUNTEXCEEDED.attributeTypeMap;
  }
}

export namespace AUTHORIZATIONAMOUNTEXCEEDED {
  export enum IssueEnum {
    AuthorizationAmountExceeded = <any>'AUTHORIZATION_AMOUNT_EXCEEDED',
  }
  export enum DescriptionEnum {
    AuthorizationAmountSpecifiedExceededAllowableLimitSpecifyADifferentAmountAndTryTheRequestAgainAlternatelyContactCustomerSupportToIncreaseYourLimitsLocalRegulationsEGInPsd2CountriesProhibitOveragesAboveTheAmountAuthorizedByThePayer = <
      any
    >'Authorization amount specified exceeded allowable limit. Specify a different amount and try the request again. Alternately, contact Customer Support to increase your limits. Local regulations (e.g. in PSD2 countries) prohibit overages above the amount authorized by the payer.',
  }
}
