/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class BILLINGAGREEMENTNOTFOUND {
  'issue'?: BILLINGAGREEMENTNOTFOUND.IssueEnum;
  'description'?: BILLINGAGREEMENTNOTFOUND.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'BILLINGAGREEMENTNOTFOUND.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'BILLINGAGREEMENTNOTFOUND.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return BILLINGAGREEMENTNOTFOUND.attributeTypeMap;
  }
}

export namespace BILLINGAGREEMENTNOTFOUND {
  export enum IssueEnum {
    BillingAgreementNotFound = <any>'BILLING_AGREEMENT_NOT_FOUND',
  }
  export enum DescriptionEnum {
    TheRequestedBillingAgreementTokenWasNotFound = <any>(
      'The requested Billing Agreement token was not found.'
    ),
  }
}
