/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class CAPTUREIDNOTFOUND {
  'issue'?: CAPTUREIDNOTFOUND.IssueEnum;
  'description'?: CAPTUREIDNOTFOUND.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'CAPTUREIDNOTFOUND.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'CAPTUREIDNOTFOUND.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return CAPTUREIDNOTFOUND.attributeTypeMap;
  }
}

export namespace CAPTUREIDNOTFOUND {
  export enum IssueEnum {
    CaptureIdNotFound = <any>'CAPTURE_ID_NOT_FOUND',
  }
  export enum DescriptionEnum {
    SpecifiedCaptureIdDoesNotExistCheckTheCaptureIdAndTryAgain = <any>(
      'Specified capture ID does not exist. Check the capture ID and try again.'
    ),
  }
}
