/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class CARDNUMBERREQUIRED {
  'issue'?: CARDNUMBERREQUIRED.IssueEnum;
  'description'?: CARDNUMBERREQUIRED.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'CARDNUMBERREQUIRED.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'CARDNUMBERREQUIRED.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return CARDNUMBERREQUIRED.attributeTypeMap;
  }
}

export namespace CARDNUMBERREQUIRED {
  export enum IssueEnum {
    CardNumberRequired = <any>'CARD_NUMBER_REQUIRED',
  }
  export enum DescriptionEnum {
    TheCardNumberIsRequiredWhenAttemptingToProcessPaymentWithCard = <any>(
      'The card number is required when attempting to process payment with card.'
    ),
  }
}
