/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CardStoredCredential } from './cardStoredCredential';

export class CardRequestAllOf {
  /**
   * The PayPal-generated ID for the vaulted payment source. This ID should be stored on the merchant\'s server so the saved payment source can be used for future transactions.
   */
  'vaultId'?: string;
  'storedCredential'?: CardStoredCredential;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'vaultId',
      baseName: 'vault_id',
      type: 'string',
    },
    {
      name: 'storedCredential',
      baseName: 'stored_credential',
      type: 'CardStoredCredential',
    },
  ];

  static getAttributeTypeMap() {
    return CardRequestAllOf.attributeTypeMap;
  }
}
