/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class CURRENCYNOTSUPPORTEDFORCOUNTRY {
  'issue'?: CURRENCYNOTSUPPORTEDFORCOUNTRY.IssueEnum;
  'description'?: CURRENCYNOTSUPPORTEDFORCOUNTRY.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'CURRENCYNOTSUPPORTEDFORCOUNTRY.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'CURRENCYNOTSUPPORTEDFORCOUNTRY.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return CURRENCYNOTSUPPORTEDFORCOUNTRY.attributeTypeMap;
  }
}

export namespace CURRENCYNOTSUPPORTEDFORCOUNTRY {
  export enum IssueEnum {
    CurrencyNotSupportedForCountry = <any>'CURRENCY_NOT_SUPPORTED_FOR_COUNTRY',
  }
  export enum DescriptionEnum {
    ForThePaymentSourceSpecifiedTheCurrencyOfTheOrderIsRestrictedByTheCountryInWhichThePayeeAccountIsBasedPleaseReferHttpsDeveloperPaypalComApiRestReferenceCurrencyCodesForListOfSupportedCurrencyCodes = <
      any
    >' For the payment_source specified, the currency of the Order is restricted by the country in which the payee account is based. Please refer https://developer.paypal.com/api/rest/reference/currency-codes/ for list of supported currency codes.',
  }
}
