/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class DOMESTICTRANSACTIONREQUIRED {
  'issue'?: DOMESTICTRANSACTIONREQUIRED.IssueEnum;
  'description'?: DOMESTICTRANSACTIONREQUIRED.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'DOMESTICTRANSACTIONREQUIRED.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'DOMESTICTRANSACTIONREQUIRED.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return DOMESTICTRANSACTIONREQUIRED.attributeTypeMap;
  }
}

export namespace DOMESTICTRANSACTIONREQUIRED {
  export enum IssueEnum {
    DomesticTransactionRequired = <any>'DOMESTIC_TRANSACTION_REQUIRED',
  }
  export enum DescriptionEnum {
    ThisTransactionRequiresThePayeeAndPayerToBeResidentInTheSameCountryADomesticTransactionIsRequiredToCreateThisPayment = <
      any
    >'This transaction requires the payee and payer to be resident in the same country, a domestic transaction is required to create this payment.',
  }
}
