/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class INVALIDPAYEEPRICINGTIERID {
  'issue'?: INVALIDPAYEEPRICINGTIERID.IssueEnum;
  'description'?: INVALIDPAYEEPRICINGTIERID.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'INVALIDPAYEEPRICINGTIERID.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'INVALIDPAYEEPRICINGTIERID.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return INVALIDPAYEEPRICINGTIERID.attributeTypeMap;
  }
}

export namespace INVALIDPAYEEPRICINGTIERID {
  export enum IssueEnum {
    InvalidPayeePricingTierId = <any>'INVALID_PAYEE_PRICING_TIER_ID',
  }
  export enum DescriptionEnum {
    PleaseCheckTheValueSpecifiedOrConfirmWithYourAccountManagerThatThePayeePricingTierIdSpecifiedHasBeenSetupForTheAccount = <
      any
    >"Please check the value specified or confirm with your Account Manager that the 'payee_pricing_tier_id' specified has been setup for the account.",
  }
}
