/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class INVALIDCOUNTRYCODE {
  'issue'?: INVALIDCOUNTRYCODE.IssueEnum;
  'description'?: INVALIDCOUNTRYCODE.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'INVALIDCOUNTRYCODE.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'INVALIDCOUNTRYCODE.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return INVALIDCOUNTRYCODE.attributeTypeMap;
  }
}

export namespace INVALIDCOUNTRYCODE {
  export enum IssueEnum {
    InvalidCountryCode = <any>'INVALID_COUNTRY_CODE',
  }
  export enum DescriptionEnum {
    CountryCodeIsInvalidPleaseReferToHttpsDeveloperPaypalComApiRestReferenceCountryCodesForAListOfSupportedCountryCodes = <
      any
    >'Country code is invalid. Please refer to https://developer.paypal.com/api/rest/reference/country-codes/ for a list of supported country codes.',
  }
}
