/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class INVALIDSTRINGLENGTH {
  'issue'?: INVALIDSTRINGLENGTH.IssueEnum;
  'description'?: INVALIDSTRINGLENGTH.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'INVALIDSTRINGLENGTH.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'INVALIDSTRINGLENGTH.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return INVALIDSTRINGLENGTH.attributeTypeMap;
  }
}

export namespace INVALIDSTRINGLENGTH {
  export enum IssueEnum {
    InvalidStringLength = <any>'INVALID_STRING_LENGTH',
  }
  export enum DescriptionEnum {
    TheValueOfAFieldIsEitherTooShortOrTooLong = <any>(
      'The value of a field is either too short or too long'
    ),
  }
}
