/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class INVALIDPREVIOUSTRANSACTIONREFERENCE {
  'issue'?: INVALIDPREVIOUSTRANSACTIONREFERENCE.IssueEnum;
  'description'?: INVALIDPREVIOUSTRANSACTIONREFERENCE.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'INVALIDPREVIOUSTRANSACTIONREFERENCE.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'INVALIDPREVIOUSTRANSACTIONREFERENCE.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return INVALIDPREVIOUSTRANSACTIONREFERENCE.attributeTypeMap;
  }
}

export namespace INVALIDPREVIOUSTRANSACTIONREFERENCE {
  export enum IssueEnum {
    InvalidPreviousTransactionReference = <any>(
      'INVALID_PREVIOUS_TRANSACTION_REFERENCE'
    ),
  }
  export enum DescriptionEnum {
    TheAuthorizationOrCaptureReferencedByPreviousTransactionReferenceIsNotValidThisCouldBeEitherBecauseThePreviousTransactionReferenceIsNotFoundOrDoesntBelongToThePayeePleaseUseAValidPreviousTransactionReference = <
      any
    >"The authorization or capture referenced by `previous_transaction_reference` is not valid. This could be either because the previous_transaction_reference is not found or doesn't belong to the payee. Please use a valid `previous_transaction_reference`.",
  }
}
