/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class MAXAUTHORIZATIONCOUNTEXCEEDED {
  'issue'?: MAXAUTHORIZATIONCOUNTEXCEEDED.IssueEnum;
  'description'?: MAXAUTHORIZATIONCOUNTEXCEEDED.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'MAXAUTHORIZATIONCOUNTEXCEEDED.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'MAXAUTHORIZATIONCOUNTEXCEEDED.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return MAXAUTHORIZATIONCOUNTEXCEEDED.attributeTypeMap;
  }
}

export namespace MAXAUTHORIZATIONCOUNTEXCEEDED {
  export enum IssueEnum {
    MaxAuthorizationCountExceeded = <any>'MAX_AUTHORIZATION_COUNT_EXCEEDED',
  }
  export enum DescriptionEnum {
    MaximumNumberOfAuthorizationAllowedForTheOrderIsReachedPleaseContactCustomerSupportIfYouNeedToIncreaseYourLimit = <
      any
    >'Maximum number of authorization allowed for the order is reached. Please contact Customer Support if you need to increase your limit.',
  }
}
