/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class MERCHANTINITIATEDWITHAUTHENTICATIONRESULTS {
  'issue'?: MERCHANTINITIATEDWITHAUTHENTICATIONRESULTS.IssueEnum;
  'description'?: MERCHANTINITIATEDWITHAUTHENTICATIONRESULTS.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'MERCHANTINITIATEDWITHAUTHENTICATIONRESULTS.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'MERCHANTINITIATEDWITHAUTHENTICATIONRESULTS.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return MERCHANTINITIATEDWITHAUTHENTICATIONRESULTS.attributeTypeMap;
  }
}

export namespace MERCHANTINITIATEDWITHAUTHENTICATIONRESULTS {
  export enum IssueEnum {
    MerchantInitiatedWithAuthenticationResults = <any>(
      'MERCHANT_INITIATED_WITH_AUTHENTICATION_RESULTS'
    ),
  }
  export enum DescriptionEnum {
    StoredPaymentSourcePaymentInitiatorMerchantIsNotSupportedIf3DSecureAuthenticationResultsArePresentInTheOrder3DSecureAuthenticationResultsCanBePresentInTheOrderOnlyWhenCustomerIsThePaymentInitiatorItIsSemanticallyIncorrectToPerformAMerchantInitiatedPaymentWith3DSecureAuthenticationResultsIsTheOrder = <
      any
    >'`stored_payment_source.payment_initiator` = `MERCHANT` is not supported if 3D-Secure authentication results are present in the order. 3D-Secure authentication results can be present in the order only when customer is the payment initiator. It is semantically incorrect to perform a merchant initiated payment with 3D-Secure authentication results is the order.',
  }
}
