/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class MISSINGPICKUPADDRESS {
  'issue'?: MISSINGPICKUPADDRESS.IssueEnum;
  'description'?: MISSINGPICKUPADDRESS.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'MISSINGPICKUPADDRESS.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'MISSINGPICKUPADDRESS.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return MISSINGPICKUPADDRESS.attributeTypeMap;
  }
}

export namespace MISSINGPICKUPADDRESS {
  export enum IssueEnum {
    MissingPickupAddress = <any>'MISSING_PICKUP_ADDRESS',
  }
  export enum DescriptionEnum {
    APickupAddressShippingAddressIsRequiredForTheProvidedShippingType = <any>(
      'A pickup address(`shipping.address`) is required for the provided `shipping.type`.'
    ),
  }
}
