/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class NOTENABLEDFORCARDPROCESSING {
  'issue'?: NOTENABLEDFORCARDPROCESSING.IssueEnum;
  'description'?: NOTENABLEDFORCARDPROCESSING.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'NOTENABLEDFORCARDPROCESSING.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'NOTENABLEDFORCARDPROCESSING.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return NOTENABLEDFORCARDPROCESSING.attributeTypeMap;
  }
}

export namespace NOTENABLEDFORCARDPROCESSING {
  export enum IssueEnum {
    NotEnabledForCardProcessing = <any>'NOT_ENABLED_FOR_CARD_PROCESSING',
  }
  export enum DescriptionEnum {
    TheRecipientForWhichTheApiCallIsMadeOnBehalfOfIsNotEnabledForCardProcessingPleaseContactPayPalCustomerSupport = <
      any
    >'The recipient for which the API call is made on behalf of is not enabled for card processing. Please contact PayPal customer support.',
  }
}
