/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class NOTSUPPORTED {
  'issue'?: NOTSUPPORTED.IssueEnum;
  'description'?: NOTSUPPORTED.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'NOTSUPPORTED.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'NOTSUPPORTED.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return NOTSUPPORTED.attributeTypeMap;
  }
}

export namespace NOTSUPPORTED {
  export enum IssueEnum {
    NotSupported = <any>'NOT_SUPPORTED',
  }
  export enum DescriptionEnum {
    ThisFieldIsNotCurrentlySupported = <any>(
      'This field is not currently supported.'
    ),
  }
}
