/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class ONEOFPARAMETERSREQUIRED {
  'issue'?: ONEOFPARAMETERSREQUIRED.IssueEnum;
  'description'?: ONEOFPARAMETERSREQUIRED.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'ONEOFPARAMETERSREQUIRED.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'ONEOFPARAMETERSREQUIRED.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return ONEOFPARAMETERSREQUIRED.attributeTypeMap;
  }
}

export namespace ONEOFPARAMETERSREQUIRED {
  export enum IssueEnum {
    OneOfParametersRequired = <any>'ONE_OF_PARAMETERS_REQUIRED',
  }
  export enum DescriptionEnum {
    OneOrMoreFieldIsRequiredToContinueWithThisRequest = <any>(
      'One or more field is required to continue with this request.'
    ),
  }
}
