/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class ONLYONEBANKSOURCEALLOWED {
  'issue'?: ONLYONEBANKSOURCEALLOWED.IssueEnum;
  'description'?: ONLYONEBANKSOURCEALLOWED.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'ONLYONEBANKSOURCEALLOWED.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'ONLYONEBANKSOURCEALLOWED.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return ONLYONEBANKSOURCEALLOWED.attributeTypeMap;
  }
}

export namespace ONLYONEBANKSOURCEALLOWED {
  export enum IssueEnum {
    OnlyOneBankSourceAllowed = <any>'ONLY_ONE_BANK_SOURCE_ALLOWED',
  }
  export enum DescriptionEnum {
    MoreThanOnePaymentMethodWithinTheBankPaymentObjectIsNotSupported = <any>(
      'More than one payment method within the bank payment object is not supported.'
    ),
  }
}
