/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrdersConfirm422IssuesInner } from './ordersConfirm422IssuesInner';

export class OrdersConfirm422 {
  'issues'?: Array<OrdersConfirm422IssuesInner>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issues',
      baseName: 'issues',
      type: 'Array<OrdersConfirm422IssuesInner>',
    },
  ];

  static getAttributeTypeMap() {
    return OrdersConfirm422.attributeTypeMap;
  }
}
