/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Information used to pay using P24(Przelewy24).
 */
export class P24 {
  /**
   * The full name representation like Mr J Smith.
   */
  'name'?: string;
  /**
   * The internationalized email address.<blockquote><strong>Note:</strong> Up to 64 characters are allowed before and 255 characters are allowed after the <code>@</code> sign. However, the generally accepted maximum length for an email address is 254 characters. The pattern verifies that an unquoted <code>@</code> sign exists.</blockquote>
   */
  'email'?: string;
  /**
   * The [two-character ISO 3166-1 code](/api/rest/reference/country-codes/) that identifies the country or region.<blockquote><strong>Note:</strong> The country code for Great Britain is <code>GB</code> and not <code>UK</code> as used in the top-level domain names for that country. Use the `C2` country code for China worldwide for comparable uncontrolled price (CUP) method, bank card, and cross-border transactions.</blockquote>
   */
  'countryCode'?: string;
  /**
   * P24 generated payment description.
   */
  'paymentDescriptor'?: string;
  /**
   * Numeric identifier of the payment scheme or bank used for the payment.
   */
  'methodId'?: string;
  /**
   * Friendly name of the payment scheme or bank used for the payment.
   */
  'methodDescription'?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'name',
      baseName: 'name',
      type: 'string',
    },
    {
      name: 'email',
      baseName: 'email',
      type: 'string',
    },
    {
      name: 'countryCode',
      baseName: 'country_code',
      type: 'string',
    },
    {
      name: 'paymentDescriptor',
      baseName: 'payment_descriptor',
      type: 'string',
    },
    {
      name: 'methodId',
      baseName: 'method_id',
      type: 'string',
    },
    {
      name: 'methodDescription',
      baseName: 'method_description',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return P24.attributeTypeMap;
  }
}
