/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class PATCHPATHREQUIRED {
  'issue'?: PATCHPATHREQUIRED.IssueEnum;
  'description'?: PATCHPATHREQUIRED.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'PATCHPATHREQUIRED.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'PATCHPATHREQUIRED.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return PATCHPATHREQUIRED.attributeTypeMap;
  }
}

export namespace PATCHPATHREQUIRED {
  export enum IssueEnum {
    PatchPathRequired = <any>'PATCH_PATH_REQUIRED',
  }
  export enum DescriptionEnum {
    PleaseSpecifyAPathForTheFieldForWhichTheOperationNeedsToBePerformed = <any>(
      "Please specify a 'path' for the field for which the operation needs to be performed."
    ),
  }
}
