/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class PAYEEACCOUNTRESTRICTED {
  'issue'?: PAYEEACCOUNTRESTRICTED.IssueEnum;
  'description'?: PAYEEACCOUNTRESTRICTED.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'PAYEEACCOUNTRESTRICTED.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'PAYEEACCOUNTRESTRICTED.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return PAYEEACCOUNTRESTRICTED.attributeTypeMap;
  }
}

export namespace PAYEEACCOUNTRESTRICTED {
  export enum IssueEnum {
    PayeeAccountRestricted = <any>'PAYEE_ACCOUNT_RESTRICTED',
  }
  export enum DescriptionEnum {
    TheMerchantAccountIsRestricted = <any>'The merchant account is restricted.',
  }
}
