/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class PAYMENTSOURCEINFOCANNOTBEVERIFIED {
  'issue'?: PAYMENTSOURCEINFOCANNOTBEVERIFIED.IssueEnum;
  'description'?: PAYMENTSOURCEINFOCANNOTBEVERIFIED.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'PAYMENTSOURCEINFOCANNOTBEVERIFIED.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'PAYMENTSOURCEINFOCANNOTBEVERIFIED.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return PAYMENTSOURCEINFOCANNOTBEVERIFIED.attributeTypeMap;
  }
}

export namespace PAYMENTSOURCEINFOCANNOTBEVERIFIED {
  export enum IssueEnum {
    PaymentSourceInfoCannotBeVerified = <any>(
      'PAYMENT_SOURCE_INFO_CANNOT_BE_VERIFIED'
    ),
  }
  export enum DescriptionEnum {
    TheCombinationOfThePaymentSourceNameBillingAddressShippingNameAndShippingAddressCouldNotBeVerifiedPleaseCorrectThisInformationAndTryAgainByCreatingANewOrder = <
      any
    >'The combination of the payment_source name, billing address, shipping name and shipping address could not be verified. Please correct this information and try again by creating a new order.',
  }
}
