/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AddressPortable2 } from './addressPortable2';
import { Name2 } from './name2';
import { PaypalWalletAttributesResponse } from './paypalWalletAttributesResponse';
import { Phone2 } from './phone2';
import { PhoneType2 } from './phoneType2';
import { TaxInfo } from './taxInfo';

/**
 * The PayPal Wallet response.
 */
export class PaypalWalletResponse {
  /**
   * The internationalized email address.<blockquote><strong>Note:</strong> Up to 64 characters are allowed before and 255 characters are allowed after the <code>@</code> sign. However, the generally accepted maximum length for an email address is 254 characters. The pattern verifies that an unquoted <code>@</code> sign exists.</blockquote>
   */
  'emailAddress'?: string;
  /**
   * The PayPal payer ID, which is a masked version of the PayPal account number intended for use with third parties. The account number is reversibly encrypted and a proprietary variant of Base32 is used to encode the result.
   */
  'accountId'?: string;
  'name'?: Name2;
  'phoneType'?: PhoneType2;
  'phoneNumber'?: Phone2;
  /**
   * The stand-alone date, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). To represent special legal values, such as a date of birth, you should use dates with no associated time or time-zone data. Whenever possible, use the standard `date_time` type. This regular expression does not validate all dates. For example, February 31 is valid and nothing is known about leap years.
   */
  'birthDate'?: string;
  'taxInfo'?: TaxInfo;
  'address'?: AddressPortable2;
  'attributes'?: PaypalWalletAttributesResponse;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'emailAddress',
      baseName: 'email_address',
      type: 'string',
    },
    {
      name: 'accountId',
      baseName: 'account_id',
      type: 'string',
    },
    {
      name: 'name',
      baseName: 'name',
      type: 'Name2',
    },
    {
      name: 'phoneType',
      baseName: 'phone_type',
      type: 'PhoneType2',
    },
    {
      name: 'phoneNumber',
      baseName: 'phone_number',
      type: 'Phone2',
    },
    {
      name: 'birthDate',
      baseName: 'birth_date',
      type: 'string',
    },
    {
      name: 'taxInfo',
      baseName: 'tax_info',
      type: 'TaxInfo',
    },
    {
      name: 'address',
      baseName: 'address',
      type: 'AddressPortable2',
    },
    {
      name: 'attributes',
      baseName: 'attributes',
      type: 'PaypalWalletAttributesResponse',
    },
  ];

  static getAttributeTypeMap() {
    return PaypalWalletResponse.attributeTypeMap;
  }
}

export namespace PaypalWalletResponse {}
