/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class PAYPALTRANSACTIONIDNOTFOUND {
  'issue'?: PAYPALTRANSACTIONIDNOTFOUND.IssueEnum;
  'description'?: PAYPALTRANSACTIONIDNOTFOUND.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'PAYPALTRANSACTIONIDNOTFOUND.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'PAYPALTRANSACTIONIDNOTFOUND.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return PAYPALTRANSACTIONIDNOTFOUND.attributeTypeMap;
  }
}

export namespace PAYPALTRANSACTIONIDNOTFOUND {
  export enum IssueEnum {
    PaypalTransactionIdNotFound = <any>'PAYPAL_TRANSACTION_ID_NOT_FOUND',
  }
  export enum DescriptionEnum {
    SpecifiedPaypalTransactionIdWasNotFoundVerifyTheValueAndTryTheRequestAgain = <
      any
    >'Specified `paypal_transaction_id` was not found. Verify the value and try the request again.',
  }
}
