/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The details of the refund status.
 */
export class RefundStatusDetails {
  /**
   * The reason why the refund has the `PENDING` or `FAILED` status.
   */
  'reason'?: RefundStatusDetails.ReasonEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'reason',
      baseName: 'reason',
      type: 'RefundStatusDetails.ReasonEnum',
    },
  ];

  static getAttributeTypeMap() {
    return RefundStatusDetails.attributeTypeMap;
  }
}

export namespace RefundStatusDetails {
  export enum ReasonEnum {
    Echeck = <any>'ECHECK',
  }
}
