/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class SHIPPINGOPTIONSNOTSUPPORTED1 {
  'issue'?: SHIPPINGOPTIONSNOTSUPPORTED1.IssueEnum;
  'description'?: SHIPPINGOPTIONSNOTSUPPORTED1.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'SHIPPINGOPTIONSNOTSUPPORTED1.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'SHIPPINGOPTIONSNOTSUPPORTED1.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return SHIPPINGOPTIONSNOTSUPPORTED1.attributeTypeMap;
  }
}

export namespace SHIPPINGOPTIONSNOTSUPPORTED1 {
  export enum IssueEnum {
    ShippingOptionsNotSupported = <any>'SHIPPING_OPTIONS_NOT_SUPPORTED',
  }
  export enum DescriptionEnum {
    ShippingOptionsAreNotSupportedWhenApplicationContextShippingPreferenceIsSetAsNoShippingOrSetProvidedAddress = <
      any
    >"Shipping options are not supported when 'application_context.shipping_preference' is set as 'NO_SHIPPING' or 'SET_PROVIDED_ADDRESS'.",
  }
}
