/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Enrolled } from './enrolled';
import { ParesStatus } from './paresStatus';

/**
 * Results of 3D Secure Authentication.
 */
export class ThreeDSecureAuthenticationResponse {
  'authenticationStatus'?: ParesStatus;
  'enrollmentStatus'?: Enrolled;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'authenticationStatus',
      baseName: 'authentication_status',
      type: 'ParesStatus',
    },
    {
      name: 'enrollmentStatus',
      baseName: 'enrollment_status',
      type: 'Enrolled',
    },
  ];

  static getAttributeTypeMap() {
    return ThreeDSecureAuthenticationResponse.attributeTypeMap;
  }
}

export namespace ThreeDSecureAuthenticationResponse {}
