/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class UNSUPPORTEDPROCESSINGINSTRUCTION {
  'issue'?: UNSUPPORTEDPROCESSINGINSTRUCTION.IssueEnum;
  'description'?: UNSUPPORTEDPROCESSINGINSTRUCTION.DescriptionEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'issue',
      baseName: 'issue',
      type: 'UNSUPPORTEDPROCESSINGINSTRUCTION.IssueEnum',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'UNSUPPORTEDPROCESSINGINSTRUCTION.DescriptionEnum',
    },
  ];

  static getAttributeTypeMap() {
    return UNSUPPORTEDPROCESSINGINSTRUCTION.attributeTypeMap;
  }
}

export namespace UNSUPPORTEDPROCESSINGINSTRUCTION {
  export enum IssueEnum {
    UnsupportedProcessingInstruction = <any>(
      'UNSUPPORTED_PROCESSING_INSTRUCTION'
    ),
  }
  export enum DescriptionEnum {
    TheSpecifiedProcessingInstructionIsNotSupportedForTheGivenPaymentSourcePleaseReferToHttpsDeveloperPaypalComApiOrdersV2DefinitionProcessingInstructionForTheListOfPaymentSourceThatCanBeSpecifiedWithThisValue = <
      any
    >'The specified processing_instruction is not supported for the given payment_source. Please refer to https://developer.paypal.com/api/orders/v2/#definition-processing_instruction for the list of payment_source that can be specified with this value.',
  }
}
