/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StoreInVaultInstruction } from './storeInVaultInstruction';

/**
 * Base vaulting specification. The object can be extended for specific use cases within each payment_source that supports vaulting.
 */
export class V3VaultInstructionBase {
  'storeInVault': StoreInVaultInstruction;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'storeInVault',
      baseName: 'store_in_vault',
      type: 'StoreInVaultInstruction',
    },
  ];

  static getAttributeTypeMap() {
    return V3VaultInstructionBase.attributeTypeMap;
  }
}

export namespace V3VaultInstructionBase {}
