/**
 * Orders
 * An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.
 *
 * The version of the OpenAPI document: 2.13
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Customizes the buyer experience during the approval process for payment with Venmo.<blockquote><strong>Note:</strong> Partners and Marketplaces might configure <code>shipping_preference</code> during partner account setup, which overrides the request values.</blockquote>
 */
export class VenmoWalletExperienceContext {
  /**
   * The business name of the merchant. The pattern is defined by an external party and supports Unicode.
   */
  'brandName'?: string;
  /**
   * The location from which the shipping address is derived.
   */
  'shippingPreference'?: VenmoWalletExperienceContext.ShippingPreferenceEnum =
    VenmoWalletExperienceContext.ShippingPreferenceEnum.GetFromFile;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'brandName',
      baseName: 'brand_name',
      type: 'string',
    },
    {
      name: 'shippingPreference',
      baseName: 'shipping_preference',
      type: 'VenmoWalletExperienceContext.ShippingPreferenceEnum',
    },
  ];

  static getAttributeTypeMap() {
    return VenmoWalletExperienceContext.attributeTypeMap;
  }
}

export namespace VenmoWalletExperienceContext {
  export enum ShippingPreferenceEnum {
    GetFromFile = <any>'GET_FROM_FILE',
    NoShipping = <any>'NO_SHIPPING',
    SetProvidedAddress = <any>'SET_PROVIDED_ADDRESS',
  }
}
