name: Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory: [
          'paypal-commercetools-events',
          'paypal-commercetools-extension',
          'paypal-commercetools-custom-application'
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ${{ matrix.directory }}/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ matrix.directory }}

      - name: Run tests
        run: npm test
        working-directory: ${{ matrix.directory }}
